run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell
    - unparam
    - bodyclose
    - nilerr

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  goimports:
    local-prefixes: github.com/JkLondon/mcp-stocks-info-server
  errcheck:
    # Для операций с кэшем, логирования и закрытия ресурсов можно исключить проверку ошибок
    exclude-functions:
      - (github.com/JkLondon/mcp-stocks-info-server/pkg/cache.Cache).Set
      - (io.Closer).Close
      - (*go.mongodb.org/mongo-driver/mongo.Cursor).Close
  gosec:
    # Исключения для gosec
    excludes:
      - G104 # Отключаем проверку необработанных ошибок (дублирует errcheck)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    # Исключаем ошибки импорта в файлах кэша
    - path: pkg/cache/cache\.go
      text: "undefined: redis"
      linters:
        - typecheck
    - path: pkg/cache/memory_cache\.go
      text: "undefined: cache"
      linters:
        - typecheck
    # Исключаем проверку ошибок для некритичных операций 
    - path: internal/adapters/repositories/apis/
      text: "Error return value of `[^`]+` is not checked"
      linters:
        - errcheck
    # Исключаем G104 для всех файлов в репозиториях
    - path: internal/adapters/repositories/
      text: "G104: Errors unhandled"
      linters:
        - gosec
    # Специальное исключение для cursor.Close
    - path: .+\.go
      text: "Error return value of `cursor.Close` is not checked"
      linters:
        - errcheck
