version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-stocks-server
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - REDIS_URI=redis:6379
      - DATABASE_NAME=${DATABASE_NAME:-stocks_db}
      - DATABASE_COLLECTION=${DATABASE_COLLECTION:-stocks}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - PORT=${PORT:-8080}
      - HOST=${HOST:-0.0.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mcp-stocks-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: mcp-stocks-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data: 